

eureka:
  instance:
    hostname: 192.168.1.1
    prefer-ip-address: true
  client:
    #    表示是否将自己注册到Eureka Server，默认为true
    registerWithEureka: true
    #    表示是否从Eureka Server获取注册信息，默认为true。
    fetchRegistry: true
    #    设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      #      defaultZone:  http://47.92.192.210:8760/eureka/,http://47.92.192.210:8761/eureka/
      defaultZone: http://127.0.0.1:8760/eureka/,http://127.0.0.1:8761/eureka/
  # 注册中心的自我保护，当注册应用下线时立即下线，开发环境使用，生产环境不使用
#  server:
#    enable-self-preservation: true

server:
  port: 9100

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/AnHuiShangJue/config-server-git  # 配置git仓库地址
          username: AnHuiShangJue
          password: shangjue0603
          search-paths: config # 配置仓库路径
      label: master  # 配置仓库的分支
