server:
  port: 8760

eureka:
  instance:
    ipAddress: 192.168.0.105
    ## prefer-ip-address: true
    ## 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    ## 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  client:
    #    表示是否将自己注册到Eureka Server，默认为true，
    registerWithEureka: true
    #    表示是否从Eureka Server获取注册信息，默认为true。
    fetchRegistry: true
    #    设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone: http://127.0.0.1:8760/eureka/
      #客户端缓存时间 默认环境下是30秒，生产环境下改成5s
      # 定时刷新本地缓存时间
    registry-fetch-interval-seconds: 5

  # 注册中心的自我保护，当注册应用下线时立即下线，开发环境使用，生产环境不使用
  server:
    enable-self-preservation: false
    ## 主动失效检测间隔,配置成5秒
    eviction-interval-timer-in-ms: 5000
    ## 禁用readOnlyCacheMap
    use-read-only-response-cache: false

spring:
  application:
    name: eureka-server-one