server:
  port: 8555
  servlet:
    context-path: /

spring:
  application:
    name: wisdom
  datasource:
    #线上
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.55.70.46:3306/wisdom?serverTimezone=GMT%2B8"useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Ahsj123456
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 10                               # 初始化提供的连接数
      max-total: 20                                 # 最大的连接数
      max-wait-millis: 200

  # 线下
#     url: jdbc:log4jdbc:mysql://192.168.0.105:3306/wisdom?useUnicode=true&characterEncoding=utf8&useSSL=true
#     username: ahsj
#     password: shangjue0603
#     driver-class-name: net.sf.log4jdbc.DriverSpy
#     type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    # 这个是配置模板路径的，默认就是templates，可不用配置
    # 这个可以不配置，检查模板位置
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5

  # 默认值为
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/

mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    cache-enabled: true   #使全局的映射器启用或禁用缓存
    lazy-loading-enabled: true  #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    aggressive-lazy-loading: true  #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
    multiple-result-sets-enabled: true #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    use-generated-keys: false #允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    use-column-label: true # 是否可以使用列的别名 (取决于驱动的兼容性) default:true
    auto-mapping-behavior: full #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    default-executor-type: simple #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    map-underscore-to-camel-case: true #使用驼峰命名法转换字段
    local-cache-scope: session #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    jdbc-type-for-null: null #设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    interceptors: #设置插件